import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
<<<<<<< HEAD
import '../styles/globals.css';

=======
>>>>>>> 2a282489217845559370a00024538c45238c110c
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
